name: Publish Identity image

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish Identity image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get version from .csproj
        id: get_version
        run: |
          chmod +x ./scripts/get-version.sh
          VERSION=$(./scripts/get-version.sh 1)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Identity image
        run: |
          cd IdentityService
          docker buildx build . \
            --tag ghcr.io/${{ github.repository_owner }}/identity-test:${{ steps.get_version.outputs.version }} \
            --tag ghcr.io/${{ github.repository_owner }}/identity-test:latest \
            --platform=linux/amd64 \
            --push \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache
