services:
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
      - "9001:9001"
      - "9002:9002"
    depends_on:
      - identity
      - helloworld
      - portainer
    networks:
      - identity-network

  identity:
    image: ghcr.io/tranduckhuy-test/identity-test:latest
    container_name: identity
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=identitydb;Database=IdentityDb;User=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;
      - JWTSettings__SecretKey=${JWT_SECRET}
      - JWTSettings__ValidIssuer=${JWT_ISSUER}
      - JWTSettings__ValidAudience=${JWT_AUDIENCE}
      - JWTSettings__ExpiryInMinutes=${JWT_EXPIRY}
      - EmailConfiguration__From=${EMAIL_FROM}
      - EmailConfiguration__SmtpServer=smtp.gmail.com
      - EmailConfiguration__Port=465
      - EmailConfiguration__Username=TimeSwap
      - EmailConfiguration__Password=${EMAIL_PASSWORD}
      - Redis__ConnectionString=redis:6379
      - Redis__InstanceName=JWT_Blacklist_
    depends_on:
      - identitydb
      - redis
    networks:
      - identity-network

  helloworld:
    image: ghcr.io/tranduckhuy-test/hello-test:latest
    container_name: helloworld
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - identity-network

  identitydb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: identitydb
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=jC4-a66adsf
    volumes:
      - identity_db:/var/opt/mssql
    ports:
      - "1433:1433"
    networks:
      - identity-network

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - identity-network

  portainer:
    image: portainer/portainer-ce:2.25.1-alpine
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - identity-network

volumes:
  identity_db:
  redis_data:
  portainer_data:

networks:
  identity-network:
    driver: bridge
