services:
  identity:
    image: ghcr.io/tranduckhuy-test/identity-test:latest
    container_name: identity
    restart: always
    ports:
      - "9000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=identitydb;Database=IdentityDb;User=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;
      - JWTSettings__SecretKey=${JWT_SECRET}
      - JWTSettings__ValidIssuer=${JWT_ISSUER}
      - JWTSettings__ValidAudience=${JWT_AUDIENCE}
      - JWTSettings__ExpiryInMinutes=${JWT_EXPIRY}
      - EmailConfiguration__From=${EMAIL_FROM}
      - EmailConfiguration__SmtpServer=smtp.gmail.com
      - EmailConfiguration__Port=465
      - EmailConfiguration__Username=TimeSwap
      - EmailConfiguration__Password=${EMAIL_PASSWORD}
      - Redis__ConnectionString=redis:6379
      - Redis__InstanceName=JWT_Blacklist_
    depends_on:
      - identitydb
      - redis

  identitydb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: identitydb
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=jC4-a66adsf
    volumes:
      - identity_db:/var/opt/mssql
    ports:
      - "1433:1433"

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  identity_db:
  redis_data:
